#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['aiomultiprocess', 'aiomultiprocess.tests']

package_data = \
{'': ['*']}

setup(name='aiomultiprocess',
      version='0.9.0',
      description='AsyncIO version of the standard multiprocessing module',
      author='John Reese',
      author_email='john@noswap.com',
      url='https://aiomultiprocess.omnilib.dev',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
